# Inisialisasi Populasi

In [1]:
import numpy as np

def init_populasi( sizepop, nchrom ):
    pop = np.random.randint(0, 2, (sizepop, nchrom))
    
    return pop

In [21]:
#untuk ujicoba saja
pop = init_populasi(2,4)
print(pop)

[[1 1 1 1]
 [0 1 0 0]]


# Kromosom

In [3]:
def dec_chrom(pop, min, max):
    sizepop, nchrom = pop.shape
    amountX = len(min)
    alele = nchrom // amountX

    copy_pop = pop.copy().reshape(sizepop, amountX, alele)

    #berdasarkan contoh kromosom pada slide perkuliahan AI 
    bagi = np.array ( [ 2 ** - (i-1) for i in range(alele) ] )
    plus = (max - min) / ( np.sum( bagi ) )

    hasildec = min + ( plus * copy_pop.dot(bagi) ) 

    return hasildec 

    

In [4]:
c = np.array( [ [ 1,1,0,0,1,0 ] ] ) #nilai dari contoh jika menggunakan kromosom genotype binner
min = np.array( [ -1 , -1] )        #batas ketentuan dari soal
max = np.array( [ 2 , 1] )          #batas ketentuan dari soal
x = dec_chrom( c, min, max )        
print(x)

[[ 1.57142857 -0.42857143]]


# Evaluasi Fitnes

In [5]:
def rumus_objektif(x):
    x1, x2 = x
    a = (np.cos(x1)*np.sin(x2)) - (x1 / ( x2**2 + 1))

    return a

In [6]:
def hfit(hasildec):

    fitness = -rumus_objektif(hasildec.T)
    return fitness

In [7]:
rumus_objektif(np.array( [ 0.089, -0.712 ] ) ) #untuk ujicoba saja

-0.709823233454355

#Roulette Wheel

In [8]:
def rwheel(fitness):
    id_ortu = []
    prob = fitness.copy()
    prob = prob / np.sum( prob )
    i = 0
    while i in range(0,3):
        r = np.random.rand()
        id, total = 0, 0
        i = i + 1
        while total < r :
            total = total + prob[id]
            id = id + 1
        id_ortu.append(id - 1)

    return id_ortu 

# CrossOver

In [9]:
def persilangan(ortu_krom, prob_cross = 0.7 ):
    _, nchrom = ortu_krom.shape

    child = ortu_krom.copy()

    r = np.random.rand()
    if r < prob_cross :
        tipot = np.random.randint(0, nchrom)
        child[ ::-1, tipot: ] = ortu_krom[ ::, tipot: ]

    return child

In [10]:
#untuk ujicoba saja
pop = init_populasi(2, 10)
anak = persilangan(pop)

print(pop)
print(anak)

[[0 1 0 0 0 1 1 0 0 1]
 [1 0 0 1 1 1 0 0 0 0]]
[[0 1 0 0 0 1 1 0 0 1]
 [1 0 0 1 1 1 0 0 0 0]]


# Mutasi

In [11]:
def mutasi(krom, prob_mut = 0.1):
    r = np.random.rand( *krom.shape )

    mutasi = krom.copy()
    termutasi = np.where( r < prob_mut, mutasi, krom )

    return termutasi

In [12]:
print (mutasi(anak)) #untuk ujicoba saja

[[0 1 0 0 0 1 1 0 0 1]
 [1 0 0 1 1 1 0 0 0 0]]


# Elitisme

In [13]:
def elitisme( pop, fitness ):
    
    idterbaik = np.argmax( fitness )
    kromterbaik = pop[idterbaik].copy()

    new_pop = np.vstack( [ kromterbaik, kromterbaik ] )

    return new_pop 

In [14]:
init_populasi(5,6) #untuk ujicoba saja

array([[0, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 1],
       [1, 1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0, 0],
       [1, 1, 0, 1, 1, 1]])

#Main Program

In [20]:
min = np.array( [ -1, -1 ] )
max = np.array( [ 2, 1 ] )
sizepop    = 50
maxgen     = 50
nchrom     = 10
prob_cross = 0.7
prob_mut   = 0.1

history = []

pop = init_populasi ( sizepop, nchrom)

for mg in range(maxgen):
    dec = dec_chrom( pop, min, max )
    fitness = hfit( dec )

    new_pop = elitisme( pop, fitness )
    history.append( np.max(fitness) )
    
    if mg%2 == 0:
        print('Generasi=',mg, 'Best Fitness=', np.max(fitness) )

    while new_pop.shape[0] < sizepop:
        id_ortu   = rwheel(fitness)
        ortu      = pop[id_ortu].copy()
        child     = persilangan(ortu, prob_cross)
        termutasi = mutasi(child, prob_mut)

        new_pop   = np.vstack( [ new_pop, termutasi ] )
    
    pop = new_pop

print('=============================================')
dec = dec_chrom(pop, min, max)
fitness = hfit(dec)
idterbaik = np.argmax(fitness)
print('Dekode Terbaik  =',dec[idterbaik])
print('Fitness Terbaik =',fitness[idterbaik])

Generasi= 0 Best Fitness= 2.0113427613973585
Generasi= 2 Best Fitness= 2.0113427613973585
Generasi= 4 Best Fitness= 2.0161198783747976
Generasi= 6 Best Fitness= 2.0216527429522126
Generasi= 8 Best Fitness= 2.0216527429522126
Generasi= 10 Best Fitness= 2.0216527429522126
Generasi= 12 Best Fitness= 2.0216527429522126
Generasi= 14 Best Fitness= 2.0216527429522126
Generasi= 16 Best Fitness= 2.0216527429522126
Generasi= 18 Best Fitness= 2.0216527429522126
Generasi= 20 Best Fitness= 2.0216527429522126
Generasi= 22 Best Fitness= 2.0216527429522126
Generasi= 24 Best Fitness= 2.0216527429522126
Generasi= 26 Best Fitness= 2.0216527429522126
Generasi= 28 Best Fitness= 2.0216527429522126
Generasi= 30 Best Fitness= 2.0216527429522126
Generasi= 32 Best Fitness= 2.0216527429522126
Generasi= 34 Best Fitness= 2.0216527429522126
Generasi= 36 Best Fitness= 2.0216527429522126
Generasi= 38 Best Fitness= 2.0216527429522126
Generasi= 40 Best Fitness= 2.0216527429522126
Generasi= 42 Best Fitness= 2.0216527429